version: "3.8"
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: participants-dynamo
    environment:
      DYNAMO_ENDPOINT: "http://participants-dynamo:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://participants-dynamo:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local
